User.create(username: "Bob", email: "bob@bob.com", bio: "I live in a shoe", password_hash: "1234")
User.create(username: "Derek", email: "bob@bob.com", bio: "I live in a hat", password_hash: "1234")
User.create(username: "Peter", email: "bob@bob.com", bio: "I live in a coat", password_hash: "1234")
User.create(username: "Philly", email: "bob@bob.com", bio: "I live in a on mars", password_hash: "1234")
User.create(username: "JLaw", email: "bob@bob.com", bio: "I live in the center of the Earth", password_hash: "1234")

Tweet.create(user_id:1, body:"first tweet!")
Tweet.create(user_id:1, body:"second tweet!")
Tweet.create(user_id:2, body:"bleh tweet!")
Tweet.create(user_id:2, body:"boom tweet!")
Tweet.create(user_id:3, body:"kaboom tweet!")
Tweet.create(user_id:4, body:"swoosh tweet!")
Tweet.create(user_id:4, body:"pike tweet!")
